# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Lazy Hacker
email: eggonlea at msn.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a lazy Linux hacker.
  Don't expect regular update!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eggonlea.github.io" # the base hostname & protocol for your site
github_username:      eggonlea
facebook_username   : eggonlea
google_plus_username: eggonlea
twitter_username:     eggonlea
linkedin_username:    eggonlea

# Build settings
markdown: kramdown

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-mentions
